version: '3.9'
services:

  app:
    build: .
    image: contas:1.0
    container_name: contas_app
    restart: unless-stopped
    tty: true
    volumes:
       - ./:/var/www
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: contas_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "222:80"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - default
    depends_on:
      - app

  mysql:
      image: mysql:latest
      container_name: mysql
      restart: unless-stopped
      env_file: .env
      environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_DATABASE: ${DB_DATABASE}
      networks:
         - default
      ports:
          - "3309:3306"
      volumes:
          - ./.db:/var/lib/mysql

  mailhog:
      image: mailhog/mailhog:latest
      restart: always
      ports:
          - ${MAIL_PORT}:1025
          - ${MAIL_PORT_WEB}:8025

networks:
  default:
    driver: bridge
